Remove legacy `$post_approval_instructions` and enforce the presence of `$services_description` (#3771)
## Description

This PR cleans up the user schema to:
1. remove `$post_approval_instructions`. This was used in the legacy
onboarding emails
2. enforce the presence of `$services_description` for services. This is
done because the normal `description` which is used in the form doesn't
seem natural on the services page. When `$services_description` is not
present, the following error will be shown:
```
> npm run build
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Collecting page data    
   Generating static pages (0/35)  [    ]Error: Service compute_cluster is missing a "$services_description" field
    at ServiceDescriptions (/home/ben/Projects/infra-config/website/.next/server/pages/docs/services.js:1:560)
    at Wc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
    at Z (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)

Error occurred prerendering page "/docs/services". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Service compute_cluster is missing a "$services_description" field
    at ServiceDescriptions (/home/ben/Projects/infra-config/website/.next/server/pages/docs/services.js:1:560)
    at Wc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
    at Z (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/ben/Projects/infra-config/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
 ✓ Generating static pages (35/35) 

> Export encountered errors on following paths:
        /docs/services
```

## Checklist
- [x] I have read and understood the [WATcloud
Guidelines](https://cloud.watonomous.ca/docs/community-docs/watcloud/guidelines)
- [x] I have performed a self-review of my code